### ISSUE TITLE
Lot sizes too big

### ISSUE THREAD

**Issue by squigglysquid** [Doomtickle/wd30#85]
In property listings, when any property has a lot size that has anything more than NUMxNUM (ex: NUMxNUMxNUM), the layout in property details is off, and in some cases, other information is being hidden because of it. Maybe we can check if there is more than one 'x' and mark those as 'Irregular' on the listings? Some properties are listed like that already.

**Comment by Doomtickle** [comment]
Need to meet and try to find a way to solve this. It's an issue for all of our sites.

**Comment by Doomtickle** [comment]
Same as #84. Can't round the numbers because they're coming through as string. Still looking for a sane way to deal with this.
